####################################################################
# Dune module information file: This file gets parsed by dunecontrol
# and by the CMake build scripts.
####################################################################

Module: opm-flowgeomechanics
Description: Simulators and utilities for automatic differentiation
Version: 2026.04-pre
Label: 2026.04-pre
Maintainer: HalvorMoll.Nilsen@sintef.no
MaintainerName: Halvor M. Nilsen
Url: http://opm-project.org
Depends: dune-istl (>= 2.9) opm-common opm-grid opm-simulators opm-upscaling
